import Head from 'next/head';
import React from 'react';
import Navbar from '@/components/Navbar';

type Props = {
  children: React.ReactNode;
};

const Layout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Chowder</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <body className="bg-gray-1" />
      </Head>

      <Navbar />
      <main className="p-4">{children}</main>
    </>
  );
};

export default Layout;
